In [1]:
import torch
import torch.nn.functional as F

In [26]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 0.5)

projection = projection[:, ::2] + projection[:, 1::2]
projection

tensor([[0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000]])

In [31]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 1)

projection = projection[:, :int(dmodel_porojected/2)]
projection

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [39]:
import torch
import torch.nn as nn

# Define the shape of the matrix
rows, cols = 5, 5

# Create a tensor with the desired shape
matrix = torch.empty(rows, cols)

# Initialize the tensor with an orthogonal matrix
nn.init.orthogonal_(matrix)

# Print the result
print("Orthogonal matrix:")
print(matrix)


Orthogonal matrix:
tensor([[-0.4937,  0.3572,  0.5475,  0.0106, -0.5734],
        [ 0.2839,  0.7766,  0.0984, -0.4482,  0.3250],
        [-0.0335,  0.4780, -0.6999,  0.4110, -0.3341],
        [-0.3068, -0.1718, -0.4335, -0.7840, -0.2714],
        [ 0.7618, -0.1062,  0.1127, -0.1238, -0.6167]])


In [40]:
import torch
import torch.nn as nn

# Define the size of the matrix
rows, cols = 5, 5

# Create a random tensor with the desired shape
matrix = torch.empty(rows, cols)

# Initialize the matrix to be orthogonal
nn.init.orthogonal_(matrix)

# Normalize each column so that its sum equals 1
matrix = matrix / matrix.sum(dim=0, keepdim=True)

# Print the result
print("Orthogonal matrix with column sums equal to 1:")
print(matrix)
print("\nColumn sums:")
print(matrix.sum(dim=0))

Orthogonal matrix with column sums equal to 1:
tensor([[ 0.3027,  0.3257, -0.1868, -1.7377, -0.6625],
        [ 0.6808, -0.0360,  1.1992,  0.0893,  0.6888],
        [ 0.6209,  0.1524, -0.8261,  1.3727,  0.0156],
        [-0.3000,  0.2734,  0.1502,  0.2809,  3.0639],
        [-0.3044,  0.2846,  0.6635,  0.9948, -2.1058]])

Column sums:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [43]:
import torch
import torch.nn.functional as F

# Define the size of the matrix
rows, cols = 10, 5

# Step 1: Generate a random non-negative matrix
matrix = torch.rand(rows, cols)  # Values are uniformly sampled from [0, 1)

# Step 2: Normalize each column so that its sum equals 1
matrix = matrix / matrix.sum(dim=0, keepdim=True)

# Print the result
print("Matrix with non-negative values and column sums equal to 1:")
print(matrix)
print("\nColumn sums:")
print(matrix.sum(dim=0))

Matrix with non-negative values and column sums equal to 1:
tensor([[0.0687, 0.1340, 0.1146, 0.1347, 0.0532],
        [0.1185, 0.0253, 0.0420, 0.0133, 0.1238],
        [0.1367, 0.0870, 0.0629, 0.0635, 0.1553],
        [0.0561, 0.1038, 0.2596, 0.0975, 0.1092],
        [0.0881, 0.1540, 0.1915, 0.2186, 0.1225],
        [0.1201, 0.0624, 0.0040, 0.0013, 0.0921],
        [0.0979, 0.0272, 0.0480, 0.1837, 0.0492],
        [0.0505, 0.1368, 0.0406, 0.0442, 0.1402],
        [0.0946, 0.1260, 0.1334, 0.1108, 0.1109],
        [0.1687, 0.1435, 0.1033, 0.1323, 0.0435]])

Column sums:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [2]:
p = torch.rand(512, 256)/256
pz = torch.zeros(512, 256)

# p = torch.rand(1, 2)
# pz = torch.zeros(1, 2)

projection_4 = torch.concat(
    (torch.concat((p, pz, pz, pz), dim=0),
    torch.concat((pz, p, pz, pz), dim=0),
    torch.concat((pz, pz, p, pz), dim=0),
    torch.concat((pz, pz, pz, p), dim=0),)
, dim=1)
# projection_4 = torch.concat((projection_4, projection_4, projection_4, projection_4), dim=1)
print(projection_4.shape)

w = torch.rand(2048, 512)

torch.Size([2048, 1024])


In [44]:
import torch

def approximate_orthogonal(rows, cols):
    # Step 1: Generate a random non-negative matrix
    matrix = torch.rand(rows, cols)
    
    # Step 2: Normalize columns to sum to 1
    matrix = matrix / matrix.sum(dim=0, keepdim=True)
    
    # Step 3: (Optional) Project onto orthogonal space (soft constraint)
    # This ensures matrix.T @ matrix is close to identity
    u, _, v = torch.svd(matrix)
    orthogonal_matrix = torch.mm(u, v.t())
    
    # Ensure non-negative and normalize columns again
    orthogonal_matrix = torch.clamp(orthogonal_matrix, min=0)
    orthogonal_matrix = orthogonal_matrix / orthogonal_matrix.sum(dim=0, keepdim=True)
    
    return orthogonal_matrix

# Example usage
rows, cols = 5, 5
approx_matrix = approximate_orthogonal(rows, cols)
print("Approximate Orthogonal Matrix with Non-Negative Values:")
print(approx_matrix)
print("\nColumn sums:")
print(approx_matrix.sum(dim=0))

Approximate Orthogonal Matrix with Non-Negative Values:
tensor([[0.1388, 0.0723, 0.0000, 0.5173, 0.0000],
        [0.5401, 0.0000, 0.0000, 0.0332, 0.3590],
        [0.3211, 0.3530, 0.5159, 0.0000, 0.0000],
        [0.0000, 0.5747, 0.0000, 0.1667, 0.3337],
        [0.0000, 0.0000, 0.4841, 0.2829, 0.3074]])

Column sums:
tensor([1., 1., 1., 1., 1.])


In [3]:
w.T.shape

torch.Size([512, 2048])

In [4]:
projection_4.T.shape

torch.Size([1024, 2048])

In [5]:
projection_4

tensor([[1.6405e-03, 4.9007e-04, 2.7963e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.7257e-03, 3.0294e-03, 1.3402e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [5.5414e-07, 1.0450e-03, 3.2509e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 3.2722e-03, 2.0382e-03,
         4.3302e-04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 3.2865e-03, 1.8893e-03,
         9.1997e-04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.6485e-03, 7.0555e-04,
         1.9422e-03]])

In [6]:
(w.T@projection_4.T)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x2048 and 1024x2048)

In [13]:


torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [16]:
P1.shape

torch.Size([2, 4])

In [17]:
W.shape

torch.Size([4, 4])

In [15]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [73]:
i = torch.rand([100, 256])
p1 = torch.rand([512, 256]) #P torch.Size([256, 512])
w = torch.rand([1536, 512]) #W torch.Size([256, 1536])
p2 = torch.rand([768, 1536]) #P torch.Size([256, 768])

In [74]:
(i@p1.T@w.T@p2.T).shape

torch.Size([100, 768])

In [5]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [6]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [28]:
DIM1 = 50257
DIM2 = 512
W = torch.rand(DIM1, DIM2)
P2 = torch.rand(DIM2, int(DIM2/2))

In [29]:
(W@P2).shape

torch.Size([502, 2])

In [7]:
# xb = 512
# yb = 2048
# xs = 256
# ys = 1024
# W = torch.rand(xb, yb)
# P1 = torch.rand(xs, xb)
# P2 = torch.rand(yb, ys)

# r = P1@W@P2
# print(W.shape)
# print(r.shape)
# r

In [9]:
from lizrd.core.misc import Linear


l = Linear(
    4, #xs
    8, #xb
    init_type = "kaiming_uniform",
    init_scale = 1.0
)
l

Linear(in_features=4, out_features=8, bias=False)