In [1]:
from transformers import GPT2Tokenizer
from transformers import RobertaTokenizer
from tokenizers.models import BPE
from copy import deepcopy
import numpy as np


/home/maciej/anaconda3/envs/tokenizex/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from bpemb import BPEmb

tokenizer = BPEmb(lang="en")


In [3]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

/home/maciej/anaconda3/envs/tokenizex/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [4]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer = RobertaTokenizer.from_pretrained("gpt2")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'RobertaTokenizer'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [5]:
from copy import deepcopy

#dev not working, need positional encoding at the first step to take in to an account!

txt = "wikipediawolna"

def text_emb_pos(txt):
    emb_pos = []
    ebm_t = []

    for i in range(1, len(txt)+1):
        et = tokenizer.encode(txt[:i])
        emb_pos.append(list(zip(et, list(range(len(et))))))
        ebm_t.append(et)

    return emb_pos, ebm_t

def create_mask(emb_pos):
    total_len = len(emb_pos)
    res = []
    mask = np.zeros([total_len, total_len])
    for embt, m in zip(emb_pos, mask):
        res.append(embt[-1])
        m[len(res)-1] = 1
        for ie in embt[:-1]:
            for j, je in enumerate(res[:-1]):
                if je == ie:
                    m[j] = 1
                    break

    return res, mask

def create_mask_embedding(txt):
    emb_pos, _ = text_emb_pos(txt)

    res, mask = create_mask(emb_pos)    

    return [e[0] for e in res], mask

emb, mask = create_mask_embedding(txt)


print(emb)
print(mask)

[50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258, 50258]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:
with open("asd.txt", "r") as f:
    all_txt = f.read()

In [7]:
from random import random


def untangle_t(emb, mask):
    emb = np.array(emb)
    mask = np.array(mask).astype(bool)
    res = []
    for m in mask:
        res.append(emb[m].tolist())
    return res

def get_imput(txt):
    bi = int(random()*(len(txt)-1000))
    return txt[bi:bi+200]



txt = get_imput(all_txt)
emb, mask = create_mask_embedding(txt)
res = untangle_t(emb, mask)
_, t = text_emb_pos(txt)

print(res)
print(t)
print(mask)
# assert(t == res)

print(len(txt))

[[50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], [50258], 

In [17]:
from time import time

C = 100
ts = 0

for _ in range(C):
    txt = get_imput(all_txt)
    t1 = time()
    emb, mask = create_mask_embedding(txt)
    t2 = time()
    ts += t2 - t1

print(ts/C)

0.029504616260528565


In [16]:
from time import time

C = 100

t1 = time()

for _ in range(C):
    txt = get_imput(all_txt)
    emb, mask = create_mask_embedding(txt)

t2 = time()
print((t2 - t1)/C)


0.030093889236450195


In [9]:
txt

"after being promised Nu's wife, Queen Saw Omma, in marriage?\n... that climate change in Asia is expected to increase flood risks in the continent's cities, which are already high for 932 million peopl"

In [10]:
tokenizer.decode([128])

'�'

In [11]:
emb.index(128)

ValueError: 128 is not in list

In [ ]:
_, e_test = text_emb_pos(txt)

res == e_test

True

In [ ]:
txt1 = 'j Wikipedię\nSzukaj\nU'